# SITE CONFIGURATION
title: 3101's blog
author: Ashar 
description: > 
  Hey, Welcome to the 3101's blog.
baseurl: ""
url: "https://coder3101.github.io/"

# SEO PLUGIN
social:
  name: Ashar
  links:
    - https://twitter.com/coder3101
    - https://www.facebook.com/coder3101
    - https://www.linkedin.com/in/coder3101
    - https://github.com/coder3101

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Let's Delve deeper in Deep Learning

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: ashar786khan@gmail.com

twitter_username: coder3101 
github_username:  coder3101 
instagram_username: coder3101 

disqus:
  shortname: coder3101

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
